/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
        "ngo": any;
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface NgoAbout {
        "ngo": any;
    }
    interface NgoContact {
        "ngo": any;
    }
    interface NgoDonate {
        "ngo": any;
    }
    interface NgoFooter {
        "ngo": any;
    }
    interface NgoHeader {
        "ngo": any;
    }
    interface NgoLegal {
        "ngo": any;
    }
    interface NgoMedia {
        "ngo": any;
    }
    interface NgoProjects {
        "ngo": any;
    }
    interface NgoProjectsDetail {
        "ngo": any;
        "projectID": string;
    }
    interface NgoTeam {
        "ngo": any;
    }
    interface NgoVolunteer {
        "ngo": any;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLNgoAboutElement extends Components.NgoAbout, HTMLStencilElement {
    }
    var HTMLNgoAboutElement: {
        prototype: HTMLNgoAboutElement;
        new (): HTMLNgoAboutElement;
    };
    interface HTMLNgoContactElement extends Components.NgoContact, HTMLStencilElement {
    }
    var HTMLNgoContactElement: {
        prototype: HTMLNgoContactElement;
        new (): HTMLNgoContactElement;
    };
    interface HTMLNgoDonateElement extends Components.NgoDonate, HTMLStencilElement {
    }
    var HTMLNgoDonateElement: {
        prototype: HTMLNgoDonateElement;
        new (): HTMLNgoDonateElement;
    };
    interface HTMLNgoFooterElement extends Components.NgoFooter, HTMLStencilElement {
    }
    var HTMLNgoFooterElement: {
        prototype: HTMLNgoFooterElement;
        new (): HTMLNgoFooterElement;
    };
    interface HTMLNgoHeaderElement extends Components.NgoHeader, HTMLStencilElement {
    }
    var HTMLNgoHeaderElement: {
        prototype: HTMLNgoHeaderElement;
        new (): HTMLNgoHeaderElement;
    };
    interface HTMLNgoLegalElement extends Components.NgoLegal, HTMLStencilElement {
    }
    var HTMLNgoLegalElement: {
        prototype: HTMLNgoLegalElement;
        new (): HTMLNgoLegalElement;
    };
    interface HTMLNgoMediaElement extends Components.NgoMedia, HTMLStencilElement {
    }
    var HTMLNgoMediaElement: {
        prototype: HTMLNgoMediaElement;
        new (): HTMLNgoMediaElement;
    };
    interface HTMLNgoProjectsElement extends Components.NgoProjects, HTMLStencilElement {
    }
    var HTMLNgoProjectsElement: {
        prototype: HTMLNgoProjectsElement;
        new (): HTMLNgoProjectsElement;
    };
    interface HTMLNgoProjectsDetailElement extends Components.NgoProjectsDetail, HTMLStencilElement {
    }
    var HTMLNgoProjectsDetailElement: {
        prototype: HTMLNgoProjectsDetailElement;
        new (): HTMLNgoProjectsDetailElement;
    };
    interface HTMLNgoTeamElement extends Components.NgoTeam, HTMLStencilElement {
    }
    var HTMLNgoTeamElement: {
        prototype: HTMLNgoTeamElement;
        new (): HTMLNgoTeamElement;
    };
    interface HTMLNgoVolunteerElement extends Components.NgoVolunteer, HTMLStencilElement {
    }
    var HTMLNgoVolunteerElement: {
        prototype: HTMLNgoVolunteerElement;
        new (): HTMLNgoVolunteerElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "ngo-about": HTMLNgoAboutElement;
        "ngo-contact": HTMLNgoContactElement;
        "ngo-donate": HTMLNgoDonateElement;
        "ngo-footer": HTMLNgoFooterElement;
        "ngo-header": HTMLNgoHeaderElement;
        "ngo-legal": HTMLNgoLegalElement;
        "ngo-media": HTMLNgoMediaElement;
        "ngo-projects": HTMLNgoProjectsElement;
        "ngo-projects-detail": HTMLNgoProjectsDetailElement;
        "ngo-team": HTMLNgoTeamElement;
        "ngo-volunteer": HTMLNgoVolunteerElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
        "ngo"?: any;
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface NgoAbout {
        "ngo"?: any;
    }
    interface NgoContact {
        "ngo"?: any;
    }
    interface NgoDonate {
        "ngo"?: any;
    }
    interface NgoFooter {
        "ngo"?: any;
    }
    interface NgoHeader {
        "ngo"?: any;
    }
    interface NgoLegal {
        "ngo"?: any;
    }
    interface NgoMedia {
        "ngo"?: any;
    }
    interface NgoProjects {
        "ngo"?: any;
    }
    interface NgoProjectsDetail {
        "ngo"?: any;
        "projectID"?: string;
    }
    interface NgoTeam {
        "ngo"?: any;
    }
    interface NgoVolunteer {
        "ngo"?: any;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "ngo-about": NgoAbout;
        "ngo-contact": NgoContact;
        "ngo-donate": NgoDonate;
        "ngo-footer": NgoFooter;
        "ngo-header": NgoHeader;
        "ngo-legal": NgoLegal;
        "ngo-media": NgoMedia;
        "ngo-projects": NgoProjects;
        "ngo-projects-detail": NgoProjectsDetail;
        "ngo-team": NgoTeam;
        "ngo-volunteer": NgoVolunteer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "ngo-about": LocalJSX.NgoAbout & JSXBase.HTMLAttributes<HTMLNgoAboutElement>;
            "ngo-contact": LocalJSX.NgoContact & JSXBase.HTMLAttributes<HTMLNgoContactElement>;
            "ngo-donate": LocalJSX.NgoDonate & JSXBase.HTMLAttributes<HTMLNgoDonateElement>;
            "ngo-footer": LocalJSX.NgoFooter & JSXBase.HTMLAttributes<HTMLNgoFooterElement>;
            "ngo-header": LocalJSX.NgoHeader & JSXBase.HTMLAttributes<HTMLNgoHeaderElement>;
            "ngo-legal": LocalJSX.NgoLegal & JSXBase.HTMLAttributes<HTMLNgoLegalElement>;
            "ngo-media": LocalJSX.NgoMedia & JSXBase.HTMLAttributes<HTMLNgoMediaElement>;
            "ngo-projects": LocalJSX.NgoProjects & JSXBase.HTMLAttributes<HTMLNgoProjectsElement>;
            "ngo-projects-detail": LocalJSX.NgoProjectsDetail & JSXBase.HTMLAttributes<HTMLNgoProjectsDetailElement>;
            "ngo-team": LocalJSX.NgoTeam & JSXBase.HTMLAttributes<HTMLNgoTeamElement>;
            "ngo-volunteer": LocalJSX.NgoVolunteer & JSXBase.HTMLAttributes<HTMLNgoVolunteerElement>;
        }
    }
}
